apiVersion: v1
kind: ServiceAccount
metadata:
  name: dpcs
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dpcs-p4target-viewer-binding
subjects:
  - kind: ServiceAccount
    name: dpcs
    namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loom-core-p4target-viewer-role
