# apiVersion: k8s.cni.cncf.io/v1
# kind: NetworkAttachmentDefinition
# metadata:
#   name: iml-cni-nginx
# spec:
#   config: '{
#     "cniVersion": "0.4.0",
#     "plugins": [
#       { 
#         "type": "imlcni", 
#         "app_id":"nginx", 
#         "app_type": "application_function"
#       }
#     ]
#   }'
# ---
# apiVersion: k8s.cni.cncf.io/v1
# kind: NetworkAttachmentDefinition
# metadata:
#   name: iml-cni-curl
# spec:
#   config: '{
#     "cniVersion": "0.4.0",
#     "plugins": [
#       { 
#         "type": "imlcni", 
#         "app_id":"curl", 
#         "app_type": "application_function"
#       }
#     ]
#   }'
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "iml-cni",
            "cni-args": {
              "app_id": "nginx",
              "app_type": "application_function"
            }
          }]
    spec:
      nodeName: "mc-a7"
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-deployment
  labels:
    app: curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "iml-cni",
            "cni-args": {
              "app_id":"curl",
              "app_type": "application_function"
            }
          }]
    spec:
      nodeName: "mc-a7"
      containers:
      - name: curl
        image: alpine/curl:8.12.1
        command: ["sh", "-c", "sleep infinity"]
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"