apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: install-iml-cni
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: install-iml-cni
  template:
    metadata:
      labels:
        app: install-iml-cni
    spec:
      tolerations:
        - operator: "Exists"  # Allow running on master and tainted nodes
      containers:
        - name: installer
          image: tomasagata/imlcni:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - name: cni-bin
              mountPath: /host/opt/cni/bin
          command:
            - /bin/sh
            - -c
            - |
              echo "Installing CNI plugin..."
              cp /app/imlcni /host/opt/cni/bin/
              chmod +x /host/opt/cni/bin/imlcni
              echo "Done. Sleeping to stay alive (or remove sleep if you want to exit)..."
              sleep infinity
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: iml-cni
spec:
  config: '{
    "cniVersion": "0.4.0",
    "type": "imlcni"
  }'


# TODO: Add a DaemonSet to create the vfbridge on all the nodes