apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iml-daemon
  namespace: desire6g-system
spec:
  selector:
    matchLabels:
      app: iml-daemon
  template:
    metadata:
      labels:
        app: iml-daemon
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - operator: "Exists"  # Allow running on master and tainted nodes
      containers:
        - name: iml-daemon
          image: tomasagata/iml-daemon:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7623
              hostPort: 7623
      initContainers:
        - name: installer
          image: tomasagata/imlcni:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - name: cni-bin
              mountPath: /host/opt/cni/bin
          command:
            - /bin/sh
            - -c
            - |
              echo "Installing CNI plugin..."
              cp /app/imlcni /host/opt/cni/bin/
              chmod +x /host/opt/cni/bin/imlcni
              echo "Done"
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: iml-cni
spec:
  config: '{
    "cniVersion": "0.4.0",
    "type": "imlcni"
  }'
