---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iml-nfvo-sa
  namespace: desire6g-system



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iml-nfvo-crb
  namespace: desire6g-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: iml-nfvo-sa
    namespace: default



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iml-nfvo
  namespace: desire6g-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iml-nfvo
  template:
    metadata:
      labels:
        app: iml-nfvo
    spec:
      nodeName: oai-01
      serviceAccountName: iml-nfvo-sa
      containers:
        - name: iml-nfvo
          image: tomasagata/iml-nfvo
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: KUBECONFIG
              value: /root/.kube/config  # This is optional, depending on how helm is used inside


---
apiVersion: v1
kind: Service
metadata:
  name: iml-nfvo
  namespace: desire6g-system
spec:
  selector:
    app: iml-nfvo
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
