site_name: IML Documentation
site_description: Documentation for the Infrastructure Management Layer (IML) project.
repo_url: https://github.com/mantra6g/iml
repo_name: mantra6g/iml

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: slate
      primary: deep orange
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Dark mode

    - scheme: default
      primary: orange
      accent: blue
      toggle:
        icon: material/weather-night
        name: Light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.instant
    - toc.integrate

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Registering and deploying your Applications: getting-started/registering-and-deploying-applications.md
    - Creating your first Programmable Target: getting-started/creating-your-first-programmable-target.md
    - Deploying a Network Function: getting-started/deploying-a-network-function.md
    - Putting everything together with a Service Chain: getting-started/first-service-chain-walkthrough.md
  - Guides:
    - Developing dynamic Network Functions: guides/overview.md
    - Application and Programmable Target setup: guides/application-and-programmable-target-setup.md
    - Network Function development: guides/network-function-development.md
  - Architecture:
    - Overview: architecture/overview.md
    - P4Target Abstraction: architecture/p4target-abstraction.md
    - Target Agents: architecture/target-agents.md
    - Network Function Development Services: architecture/network-function-development-services.md
    - IML Networking Plugin: architecture/iml-networking-plugin.md
  - API:
    - Overview: api/overview.md
    - Applications: api/applications.md
    - Network Functions: api/network-functions.md
    - Service Chains: api/service-chains.md
    - P4Targets: api/p4targets.md
    - BMv2Target: api/bmv2target.md
  - Contributing: contributing/contributing.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - tables

plugins:
  - search

extra_javascript:
  - js/readthedocs.js
