# Example values:
# -------------------------------------------------------
#   nfrouter:
#     node: "node-01"
#   pkt_src:
#     if_name: "nfr-f4bc"
#     mac: "00:11:22:33:44:55"
#     ip: "10.226.255.53"
#   pkt_dst:
#     if_name: "nfr-09ab"
#     mac: "66:77:88:99:AA:BB"
#     ip: "10.179.48.77"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfrouter
spec:
  selector:
    matchLabels:
      app: nfrouter
  template:
    metadata:
      labels:
        app: nfrouter
      annotations:
        k8s.v1.cni.cncf.io/networks: '{ "name": "iml-cni", "cni-args": {"app_type": "network_function", "src_if": "{{Values.pkt_src.if_name}}", "dst_if": "{{Values.pkt_dst.if_name}}"} }'
    spec:
      nodeName: {{ Values.nfrouter.node }}
      containers:
      - name: nfrouter
        image: tomasagata/nfrouter:latest
        args: [ './l3fwd-static -l 0-1 -n 4 --no-pci --vdev=net_tap0,iface=dtap0,remote={{Values.pkt_src.if_name}} --vdev=net_tap1,iface=dtap1,remote={{Values.pkt_dst.if_name}} -- -p 0x3 --config="(0,0,0),(0,1,1),(1,0,0),(1,1,1)" --mode=poll -P --eth-dest=0,{{Values.pkt_src.mac}} --eth-dest=1,{{Values.pkt_dst.mac}} --rule_ipv4="/opt/nfconfig/ipv4rules.cfg" --rule_ipv6="/opt/nfconfig/ipv6rules.cfg"' ]
        volumeMounts:
          - name: nf-config
            mountPath: /opt/nfconfig
      volumes:
      - name: nf-config
        configMap:
          name: nfrouter-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nfrouter-config
data:
  ipv4rules.cfg: |
    R{{Values.pkt_src.ip}}/32 0
    R{{Values.pkt_dst.ip}}/32 1
  ipv6rules.cfg: R::/128 0