# Example values:
# -------------------------------------------------------
#   nfrouters:
#   - name: "nfrouter-abcd"
#     node: "node-01"
#     interfaces:
#     - name: "nfr-f4bc"
#       peer_mac: "00:11:22:33:44:55"
#       peer_ip: "10.100.1.1"
#     - name: "nfr-09ab"
#       peer_mac: "66:77:88:99:AA:BB"
#       peer_ip: "10.100.2.2"
#   - name: "nfrouter-ef01"
#     node: "node-01"
#     interfaces:
#     - name: "nfr-0cde"
#       peer_mac: "CC:DD:EE:FF:00:11"
#       peer_ip: "10.100.3.3"
#     - name: "nfr-0fgh"
#       peer_mac: "22:33:44:55:66:77"
#       peer_ip: "10.100.4.4"

{{- range $nfrouter_index, $nfrouter := .Values.nfrouters }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  ipv4rules.cfg: |
{{- range $index, $intf := $nfrouter.interfaces }}
    R{{ $intf.peer_ip }}/32 {{ $index }}
{{- end }}
  ipv6rules.cfg: R::/128 0
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $nfrouter.name }}
spec:
  selector:
    matchLabels:
      app: {{ $nfrouter.name }}
  template:
    metadata:
      labels:
        app: {{ $nfrouter.name }}
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "iml-cni",
            "namespace": "default",
            "cni-args": {
              "app_type": "network_function",
              "interfaces": [
              {{- range $index, $intf := $nfrouter.interfaces }}
                {{ if $index }},{{ end }}
                {{ $intf.name }}
              {{- end }}
              ]
            }
          }]
    spec:
      nodeName: {{ $nfrouter.node }}
      containers:
      - name: {{ $nfrouter.name }}
        image: tomasagata/nfrouter:latest
        securityContext:
          privileged: true
        args: [
          './l3fwd-static', 
          '-l', '0-1', 
          '-n', '4', 
          '--no-pci', 
        {{- range $index, $intf := $nfrouter.interfaces }}
          '--vdev=net_tap{{$index}},iface=dtap{{$index}},remote={{$intf.name}}',
        {{- end }}
          '--', 
          '-p', '0x3',
          '--config="(0,0,0),(0,1,1),(1,0,0),(1,1,1)"',
          '--mode=poll', '-P',
        {{- range $index, $intf := $nfrouter.interfaces }}
          '--eth-dest={{$index}},{{$intf.peer_mac}}',
        {{- end }}
          '--rule_ipv4=/opt/nfconfig/ipv4rules.cfg',
          '--rule_ipv6=/opt/nfconfig/ipv6rules.cfg',
        ]
        volumeMounts:
          - name: hugepage
            mountPath: /hugepages
          - name: nf-config
            mountPath: /opt/nfconfig
        resources:
          limits:
            hugepages-1Gi: 1Gi
            memory: 1Gi
            nvidia.com/cx6dx_vf: '1'
          requests:
            hugepages-1Gi: 1Gi
            memory: 1Gi
            nvidia.com/cx6dx_vf: '1'
      volumes:
      - name: hugepage
        emptyDir:
          medium: HugePages
      - name: nf-config
        configMap:
          name: nfrouter-config

{{ end -}}
