apiVersion: cache.desire6g.eu/v1alpha1
kind: Application
metadata:
  name: web-client-1
  namespace: default
spec: 
  override_id: dead-beef-1
---
apiVersion: cache.desire6g.eu/v1alpha1
kind: Application
metadata:
  name: web-client-2
  namespace: default
spec: 
  override_id: dead-beef-2
---
apiVersion: cache.desire6g.eu/v1alpha1
kind: Application
metadata:
  name: web-server
  namespace: default
spec: 
  override_id: face-feed
---
apiVersion: cache.desire6g.eu/v1alpha1
kind: NetworkFunction
metadata:
  name: pkt-logger
  namespace: default
spec: 
  replicas: 1
  type: multiplexed
  subFunctions:
  - name: logger-1
    id: 1
    code: https://raw.githubusercontent.com/DESIRE6G/IML-LNFVO/refs/heads/tomas/feat/srv6/examples/verified/program1.p4
  - name: logger-2
    id: 2
    code: https://raw.githubusercontent.com/DESIRE6G/IML-LNFVO/refs/heads/tomas/feat/srv6/examples/verified/program2.p4
---
  apiVersion: cache.desire6g.eu/v1alpha1
  kind: ServiceChain
  metadata:
    name: client-1-to-server
    namespace: default
  spec:
    from:
      name: web-client-1
      namespace: default
    to:
      name: web-server
      namespace: default
    functions:
    - name: pkt-logger
      namespace: default
      subFunctionID: 1
---
apiVersion: cache.desire6g.eu/v1alpha1
kind: ServiceChain
metadata:
  name: client-2-to-server
  namespace: default
spec:
  from:
    name: web-client-2
    namespace: default
  to:
    name: web-server
    namespace: default
  functions:
  - name: pkt-logger
    namespace: default
    subFunctionID: 2