apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: web-client-1
  namespace: default
spec: 
  override_id: dead-beef-1
---
apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: web-client-2
  namespace: default
spec: 
  override_id: dead-beef-2
---
apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: web-server
  namespace: default
spec: 
  override_id: face-feed
---
apiVersion: core.loom.io/v1alpha1
kind: NetworkFunction
metadata:
  name: pkt-logger
  namespace: default
spec: 
  replicas: 1
  type: multiplexed
  subFunctions:
  - name: logger-1
    id: 1
  - name: logger-2
    id: 2
  containers:
    - name: control-plane
      image: tomasagata/multiplexed-nf:latest
    - name: bmv2-switch
      image: p4lang/p4c:latest
      command: [ "simple_switch_grpc", 
        "--no-p4", 
        "-i 1@iml0", 
        "--log-console",
        "--log-level", "info",
        "--",
        "--grpc-server-addr", "0.0.0.0:9559", 
        "--cpu-port", "111"
      ]
---
  apiVersion: core.loom.io/v1alpha1
  kind: ServiceChain
  metadata:
    name: client-1-to-server
    namespace: default
  spec:
    from:
      name: web-client-1
      namespace: default
    to:
      name: web-server
      namespace: default
    functions:
    - name: pkt-logger
      namespace: default
      subFunctionID: 1
---
apiVersion: core.loom.io/v1alpha1
kind: ServiceChain
metadata:
  name: client-2-to-server
  namespace: default
spec:
  from:
    name: web-client-2
    namespace: default
  to:
    name: web-server
    namespace: default
  functions:
  - name: pkt-logger
    namespace: default
    subFunctionID: 2