apiVersion: scheduling.loom.io/v1alpha1
kind: NetworkFunctionReplicaSet
metadata:
  labels:
    app.kubernetes.io/name: loom-operator
    app.kubernetes.io/managed-by: kustomize
  name: networkfunctionreplicaset-sample
spec:
  # TODO(user): Add fields here
