---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.desire6g.eu
  resources:
  - applications
  - networkfunctions
  - servicechains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.desire6g.eu
  resources:
  - applications/finalizers
  - networkfunctions/finalizers
  - servicechains/finalizers
  verbs:
  - update
- apiGroups:
  - cache.desire6g.eu
  resources:
  - applications/status
  - networkfunctions/status
  - servicechains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.desire6g.eu
  resources:
  - p4targets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.desire6g.eu
  resources:
  - p4targets/finalizers
  verbs:
  - update
- apiGroups:
  - core.desire6g.eu
  resources:
  - p4targets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.desire6g.eu
  resources:
  - p4targetdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.desire6g.eu
  resources:
  - p4targetdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - infra.desire6g.eu
  resources:
  - p4targetdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scheduling.desire6g.eu
  resources:
  - networkfunctionbindings
  - networkfunctionreplicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.desire6g.eu
  resources:
  - networkfunctionbindings/finalizers
  - networkfunctionreplicasets/finalizers
  verbs:
  - update
- apiGroups:
  - scheduling.desire6g.eu
  resources:
  - networkfunctionbindings/status
  - networkfunctionreplicasets/status
  verbs:
  - get
  - patch
  - update
