apiVersion: v1
kind: ServiceAccount
metadata:
  name: iml-daemon
  namespace: desire6g-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iml-daemon-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iml-daemon-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iml-daemon-role
subjects:
  - kind: ServiceAccount
    name: iml-daemon
    namespace: desire6g-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iml-daemon
  namespace: desire6g-system
spec:
  selector:
    matchLabels:
      app: iml-daemon
  template:
    metadata:
      labels:
        app: iml-daemon
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      serviceAccountName: iml-daemon
      initContainers:
        - name: iml-cni-installer
          image: tomasagata/iml-cni:latest
          command:
            - /bin/sh
            - -c
            - |
              cp /app/imlcni /host/opt/cni/bin/
              chmod +x /host/opt/cni/bin/imlcni
          securityContext:
            privileged: true
          volumeMounts:
            - name: cni-bin
              mountPath: /host/opt/cni/bin
      containers:
        - name: iml-daemon
          image: tomasagata/iml-daemon:latest
          command:
            - ./iml-daemon
          resources:
            requests:
              cpu: 1000m
              memory: 2048Mi
            limits:
              cpu: 2000m
              memory: 4096Mi
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
