apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - iml_configmap.yaml

configMapGenerator:
  - name: bmv2-config
    files:
      - bmv2_configmap.yaml
    literals:
      - bmv2-data-plane-image=p4lang/behavioral-model:latest
      - bmv2-control-plane-image=mantra6g/bmv2-driver:latest

generatorOptions:
  disableNameSuffixHash: true
