apiVersion: infra.desire6g.eu/v1alpha1
kind: P4TargetDeployment
metadata:
  labels:
    app.kubernetes.io/name: builder
    app.kubernetes.io/managed-by: kustomize
  name: p4targetdeployment-sample
spec:
  # TODO(user): Add fields here
