---
apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: local-web-proxy
  namespace: default
spec: {}
#---
#apiVersion: core.loom.io/v1alpha1
#kind: Application
#metadata:
#  name: local-streaming-proxy
#  namespace: default
#spec: {}
---
apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  #name: dummy-web-server
  name: web-server
  namespace: default
spec: {}
#---
#apiVersion: core.loom.io/v1alpha1
#kind: Application
#metadata:
#  #name: dummy-streaming-server
#  name: streaming-server
#  namespace: default
#spec: {}
