---
apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: local-web-proxy
  namespace: default
spec: {}
---
apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: local-streaming-proxy
  namespace: default
spec: {}
---
apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: dummy-web-server
  namespace: default
spec: {}
---
apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: dummy-streaming-server
  namespace: default
spec: {}
---
apiVersion: core.loom.io/v1alpha1
kind: NetworkFunction
metadata:
  name: qos
  namespace: default
  labels:
    nf: qos
spec:
  p4File: ./qos.p4
  targetSelector:
    matchLabels:
      p4target.loom.io/arch: v1model
---
apiVersion: core.loom.io/v1alpha1
kind: NetworkFunction
metadata:
  name: traffic-manager
  namespace: default
  labels:
    nf: traffic-manager
spec:
  p4File: ./traffic-manager.p4
#  configRef:
#    name: my-nf-config
  targetSelector:
    matchLabels:
      p4target.loom.io/arch: v1model
---
apiVersion: core.loom.io/v1alpha1
kind: NetworkFunction
metadata:
  name: web-lb
  namespace: default
  labels:
    nf: web-lb
spec:
  p4File: ./web-lb.p4
  targetSelector:
    matchLabels:
      p4target.loom.io/arch: v1model
---
apiVersion: core.loom.io/v1alpha1
kind: NetworkFunction
metadata:
  name: streaming-lb
  namespace: default
  labels:
    nf: streaming-lb
spec:
  p4File: ./streaming-lb.p4
  targetSelector:
    matchLabels:
      p4target.loom.io/arch: v1model
---
#apiVersion: core.loom.io/v1alpha1
#kind: NetworkFunctionConfig
#metadata:
#  name: my-nf-config
#spec:
#  table: my_table
#  entries:
#    - match:
#        field1: value1
#        field2: value2
#      action:
#        name: my_action
#        params:
#          param1: value1
---
apiVersion: infra.loom.io/v1alpha1
kind: BMv2Target
metadata:
  name: bmv2-target-1
spec:
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"

---
apiVersion: core.loom.io/v1alpha1
kind: ServiceChain
metadata:
  name: web-uplink
  namespace: default
spec:
  from:
    name: local-web-proxy
    namespace: default
  to:
    name: dummy-web-server
    namespace: default
  functions:
    - matchLabels:
        nf: web-lb
---
apiVersion: core.loom.io/v1alpha1
kind: ServiceChain
metadata:
  name: web-downlink
  namespace: default
spec:
  from:
    name: dummy-web-server
    namespace: default
  to:
    name: local-web-proxy
    namespace: default
  functions:
    - matchLabels:
        nf: traffic-manager
---
apiVersion: core.loom.io/v1alpha1
kind: ServiceChain
metadata:
  name: streaming-uplink
  namespace: default
spec:
  from:
    name: local-streaming-proxy
    namespace: default
  to:
    name: dummy-streaming-server
    namespace: default
  functions:
    - matchLabels:
        nf: streaming-lb
---
apiVersion: core.loom.io/v1alpha1
kind: ServiceChain
metadata:
  name: streaming-downlink
  namespace: default
spec:
  from:
    name: dummy-streaming-server
    namespace: default
  to:
    name: local-streaming-proxy
    namespace: default
  functions:
    - matchLabels:
        nf: qos
        nf: traffic-manager
