---
apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: local-web-proxy
  namespace: default
spec: {}
---
apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: local-streaming-proxy
  namespace: default
spec: {}
---
apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: dummy-web-server
  namespace: default
spec: {}
---
apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: dummy-streaming-server
  namespace: default
spec: {}
---
apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: web-server
  namespace: default
spec: {}
---
apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: streaming-server
  namespace: default
spec: {}
---
apiVersion: core.loom.io/v1alpha1
kind: NetworkFunction
metadata:
  name: qos
  namespace: default
  labels:
    nf: qos
spec:
  p4File: https://raw.githubusercontent.com/mantra6g/iml/refs/heads/demo_pl2days_webproxy/examples/demo/qos/qos.p4
  targetSelector:
    p4target.loom.io/arch: v1model
---
apiVersion: core.loom.io/v1alpha1
kind: NetworkFunction
metadata:
  name: traffic-manager
  namespace: default
  labels:
    nf: traffic-manager
spec:
  p4File: https://raw.githubusercontent.com/mantra6g/iml/refs/heads/demo_pl2days_webproxy/examples/demo/traffic-manager/tm.p4
#  configRef:
#    name: my-nf-config
  targetSelector:
    p4target.loom.io/arch: v1model
---
apiVersion: core.loom.io/v1alpha1
kind: NetworkFunction
metadata:
  name: web-lb
  namespace: default
  labels:
    nf: web-lb
spec:
  p4File: https://raw.githubusercontent.com/mantra6g/iml/refs/heads/demo_pl2days_webproxy/examples/demo/load-balancer/lb.p4
  configRef:
    name: web-lb-config
  targetSelector:
    p4target.loom.io/arch: v1model
---
apiVersion: core.loom.io/v1alpha1
kind: NetworkFunction
metadata:
  name: streaming-lb
  namespace: default
  labels:
    nf: streaming-lb
spec:
  p4File: https://raw.githubusercontent.com/mantra6g/iml/refs/heads/demo_pl2days_webproxy/examples/demo/load-balancer/lb.p4
  configRef:
    name: streaming-lb-config
  targetSelector:
    p4target.loom.io/arch: v1model
---
apiVersion: core.loom.io/v1alpha1
kind: NetworkFunctionConfig
metadata:
  name: streaming-lb-config
spec: {}
---
apiVersion: core.loom.io/v1alpha1
kind: NetworkFunctionConfig
metadata:
  name: web-lb-config
spec: {}
---
apiVersion: infra.loom.io/v1alpha1
kind: BMv2Target
metadata:
  name: bmv2-target-1
spec:
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"
---
apiVersion: infra.loom.io/v1alpha1
kind: BMv2Target
metadata:
  name: bmv2-target-2
spec:
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"
---
apiVersion: infra.loom.io/v1alpha1
kind: BMv2Target
metadata:
  name: bmv2-target-3
spec:
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"
---
apiVersion: infra.loom.io/v1alpha1
kind: BMv2Target
metadata:
  name: bmv2-target-4
spec:
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"
---
apiVersion: core.loom.io/v1alpha1
kind: ServiceChain
metadata:
  name: web-uplink
  namespace: default
spec:
  from:
    name: local-web-proxy
    namespace: default
  to:
    name: dummy-web-server
    namespace: default
  functions:
  - matchLabels:
      nf: web-lb
---
apiVersion: core.loom.io/v1alpha1
kind: ServiceChain
metadata:
  name: web-downlink
  namespace: default
spec:
  from:
    name: web-server
    namespace: default
  to:
    name: local-web-proxy
    namespace: default
  functions:
#  - matchLabels:
#      nf: traffic-manager
  - matchLabels:
      nf: web-lb
---
apiVersion: core.loom.io/v1alpha1
kind: ServiceChain
metadata:
  name: streaming-uplink
  namespace: default
spec:
  from:
    name: local-streaming-proxy
    namespace: default
  to:
    name: dummy-streaming-server
    namespace: default
  functions:
  - matchLabels:
      nf: streaming-lb
---
apiVersion: core.loom.io/v1alpha1
kind: ServiceChain
metadata:
  name: streaming-downlink
  namespace: default
spec:
  from:
    name: streaming-server
    namespace: default
  to:
    name: local-streaming-proxy
    namespace: default
  functions:
#  - matchLabels:
#      nf: qos
#  - matchLabels:
#      nf: traffic-manager
  - matchLabels:
      nf: streaming-lb
