---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: local-web-proxy
  ports:
    - name: iperf3-tcp
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007
    - name: iperf3-udp
      protocol: UDP
      port: 3000
      targetPort: 3000
      nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: iperf-streaming-service
spec:
  type: NodePort
  selector:
    app: local-streaming-proxy
  ports:
  - name: iperf3-ctrl
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30008
  - name: iperf3-data
    protocol: UDP
    port: 3000
    targetPort: 3000
    nodePort: 30008
