apiVersion: core.desire6g.eu/v1alpha1
kind: Application
metadata:
  name: web-client
  namespace: default
spec: 
  override_id: dead-beef
---
apiVersion: core.desire6g.eu/v1alpha1
kind: Application
metadata:
  name: web-server
  namespace: default
spec: 
  override_id: face-feed
---
apiVersion: core.desire6g.eu/v1alpha1
kind: NetworkFunction
metadata:
  name: pkt-logger
  namespace: default
spec:
  type: simple
  replicas: 1
  containers:
    - name: pkt-logger
      image: tomasagata/pkt-logger:latest
---
apiVersion: core.desire6g.eu/v1alpha1
kind: ServiceChain
metadata:
  name: client-server-with-logger
  namespace: default
spec:
  from:
    name: web-client
    namespace: default
  to:
    name: web-server
    namespace: default
  functions:
  - name: pkt-logger
    namespace: default