all:
  hosts:
    node1:
      ansible_host: <CHANGE>
      ansible_user: <CHANGE>
      vf_iface: <CHANGE>
      sriov_vendor: '8086' # Intel. MUST CHANGE if you use other vendor. Use "sudo lspci -nn"
      sriov_dev: '1521' # I350. MUST CHANGE if you use other device. Use "sudo lspci -nn"
    node2:
      ansible_host: <CHANGE>
      ansible_user: <CHANGE>
      vf_iface: <CHANGE>
      sriov_vendor: '8086' # Intel. MUST CHANGE if you use other vendor. Use "sudo lspci -nn"
      sriov_dev: '1563' # 10G X550T. MUST CHANGE if you use other device. Use "sudo lspci -nn"
  children:
    k8s_controls:
      hosts:
        node1:
    k8s_workers:
      hosts:
        node1:
        node2:
