apiVersion: core.loom.io/v1alpha1
kind: NetworkFunctionConfig
metadata:
  labels:
    app.kubernetes.io/name: loom-operator
    app.kubernetes.io/managed-by: kustomize
  name: networkfunctionconfig-sample
spec:
  # TODO(user): Add fields here
