apiVersion: apps/v1
kind: Deployment
metadata:
  name: iml-p4-controller
  namespace: desire6g-system
  labels:
    app: p4controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p4controller
  template:
    metadata:
      labels:
        app: p4controller
    spec:
      containers:
        - name: p4controller
          image: tomasagata/p4runtime-controller:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: iml-p4-controller
  namespace: desire6g-system
spec:
  selector:
    app: p4controller
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
