apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: web-client
  namespace: default
spec: {}
---
apiVersion: core.loom.io/v1alpha1
kind: Application
metadata:
  name: web-server
  namespace: default
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "loom-cni", 
              "cni-args": {
                "app_name": "web-server",
                "app_namespace": "default"
              }
            }
          ]
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  namespace: default
spec:
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "loom-cni",
              "cni-args": {
                "app_name": "web-client",
                "app_namespace": "default"
              }
            }
          ]
    spec:
      containers:
        - name: web-client
          image: alpine:3.20