apiVersion: cache.desire6g.eu/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: default
spec: 
  override_id: face-feed
---
apiVersion: cache.desire6g.eu/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: default
spec: 
  override_id: dead-beef
---
apiVersion: cache.desire6g.eu/v1alpha1
kind: ServiceChain
metadata:
  name: nginx-mongodb
  namespace: default
spec:
  from:
    name: nginx
    namespace: default
  to:
    name: mongodb
    namespace: default