apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "iml-cni", 
              "cni-args": {
                "app_type": "application_function",
                "app_id": "11b61d80-0421-458a-a193-17807f4ece16"
              }
            }
          ]
    spec:
      nodeSelector:
        kubernetes.io/hostname: oai-01
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mongodb
#   namespace: default
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mongodb
#   template:
#     metadata:
#       labels:
#         app: mongodb
#       annotations:
#         k8s.v1.cni.cncf.io/networks: |
#           [
#             { 
#               "name": "iml-cni",
#               "cni-args": {
#                 "app_type": "application_function",
#                 "app_id": "1a63432d-7e00-4da4-ac3c-17ab962e8024"
#               }
#             }
#           ]
#     spec:
#       nodeSelector:
#         kubernetes.io/hostname: oai-01
#       containers:
#         - name: mongodb
#           image: mongo:latest
#           ports:
#             - containerPort: 27017