apiVersion: core.loom.io/v1alpha1
kind: NetworkFunctionConfig
metadata:
  name: pkt-logger-config
  namespace: default
spec:
  tables:
    log_table:
      entries:
        - matchFields:
          - name: hdr.inner_ipv4.src_addr
            type: Exact
            exact:
              ipv4Address: 10.123.0.1
          action:
            name: log
