name: 'Test go packages and build container images'

on:
  push:
    branches: [ main ]
    paths: &paths
      - go.work
      - go.work.sum
      - cni/**
      - api/**
      - daemon/**
      - operator/**
      - targets/bmv2/**
  pull_request:
    branches: [ main ]
    paths: *paths

jobs:
  # changes:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     pull-requests: read
  #   outputs:
  #     images: ${{ steps.filter.outputs.changes }}
  #   steps:
  #   - uses: actions/checkout@v6
  #   - uses: dorny/paths-filter@v4
  #     id: filter
  #     with:
  #       filters: |
  #         cni: ['cni/**', 'api/**', 'go.work', 'go.work.sum']
  #         daemon: ['daemon/**', 'api/**', 'go.work', 'go.work.sum']
  #         operator: ['operator/**', 'api/**', 'go.work', 'go.work.sum']

  test-and-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        target: ['operator']
    env:
      ENVTEST_K8S_VERSION: 1.34.1
      GINKGO_NO_COLOR: TRUE

    steps:
      - run: echo "$ENVTEST_K8S_VERSION" > k8sver
      - uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - name: Set up Go
        id: setupgo
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.2'
          cache: true
          #cache-dependency-path: '**/go.mod'
          cache-dependency-path: |
            k8sver
            tools/go.mod
            operator/go.mod

      - name: Cache envtest
        id: cache-envtest
        uses: actions/cache@v6
        with:
          path: tools/bin
          key: "envtest-${{ env.ENVTEST_K8S_VERSION }}"

      - name: Run setup-envtest
        run: |
          echo "KUBEBUILDER_ASSETS=${{ github.workspace }}/tools/$(go -C tools tool setup-envtest use ${ENVTEST_K8S_VERSION} --bin-dir ./bin -p path)" >> "$GITHUB_ENV"

      - name: Run tests with coverage
        run: |
          set +e
          go -C tools tool gotestsum --no-color --junitfile unit-tests.xml -- -coverprofile=coverage.out ../operator/...
          test_exit_code=$?
          ls -lah tools
          go tool cover -html=./tools/coverage.out -o ./tools/coverage.html
          go -C tools tool gocover-cobertura < ./tools/coverage.out > ./tools/coverage.xml
          exit "$test_exit_code"

      #- name: Publish Test Report
      #  uses: mikepenz/action-junit-report@v6
      #  if: success() || failure() # always run even if the previous step fails
      #  with:
      #    report_paths: unit-tests.xml
      #    detailed_summary: true
      #    include_passed: true
      #    include_time_in_summary: true

      - name: Generate unit test summary
        if: "!cancelled()"
        uses: test-summary/action@v2
        with:
          paths: "tools/unit-tests.xml"

      - name: Generate coverage summary
        if: "!cancelled()"
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "./tools/coverage.xml"
          format: markdown
          output: file

      - name: Upload coverage as artifact
        if: "!cancelled()"
        uses: actions/upload-artifact@v7
        with:
          path: "tools/coverage.html"
          archive: false

      - name: Write coverage to job summary
        if: "!cancelled()"
        run: cat ./code-coverage-results.md >> $GITHUB_STEP_SUMMARY

  build-and-push:
    runs-on: ubuntu-latest
    # needs: changes
    needs: test-and-coverage
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        # target: ${{ fromJSON(needs.changes.outputs.images) }}
        target: ['cni', 'daemon', 'operator', 'bmv2']
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.target }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Log in to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build image
        uses: docker/build-push-action@v7
        with:
          platforms: linux/amd64 # ,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          target: ${{ matrix.target }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
